"""removed fields 'active' 

Revision ID: 91acd9221291
Revises: 96c27aaa6ffa
Create Date: 2020-11-24 19:35:49.251202

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91acd9221291'
down_revision = '96c27aaa6ffa'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('normative', 'active')
    op.drop_column('substances', 'active')
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('substances', sa.Column('active', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('normative', sa.Column('active', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
