"""changed format Normative.output from Numeric to Integer

Revision ID: bac6cdbeb7f9
Revises: 91acd9221291
Create Date: 2020-11-24 21:36:37.837630

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bac6cdbeb7f9'
down_revision = '91acd9221291'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
