"""modified model solution

Revision ID: f03d5ae5d924
Revises: 6e6a276b0402
Create Date: 2020-11-29 19:22:32.752352

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f03d5ae5d924'
down_revision = '6e6a276b0402'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('solutions', sa.Column('measurement', sa.String(), nullable=True))
    op.add_column('solutions', sa.Column('price', sa.Numeric(), nullable=True))
    op.add_column('solutions', sa.Column('total_cost', sa.Numeric(), nullable=True))
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('solutions', 'total_cost')
    op.drop_column('solutions', 'price')
    op.drop_column('solutions', 'measurement')
    # ### end Alembic commands ###
