"""init

Revision ID: 29c873fc2299
Revises: 
Create Date: 2020-12-08 20:13:00.168533

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29c873fc2299'
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analysis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recipe_name', sa.String(length=255), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('done_date', sa.Date(), nullable=True),
    sa.Column('total_cost', sa.Integer(), nullable=True),
    sa.Column('substances_cost', sa.JSON(), nullable=True),
    sa.Column('solutions_cost', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_analysis'))
    )
    op.create_table('normatives',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('output', sa.Numeric(), nullable=True),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_normatives')),
    sa.UniqueConstraint('name', name=op.f('uq_normatives_name'))
    )
    op.create_table('recipes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('substances', sa.JSON(), nullable=True),
    sa.Column('solutions', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recipes')),
    sa.UniqueConstraint('name', name=op.f('uq_recipes_name'))
    )
    op.create_table('solutions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('normative', sa.String(length=255), nullable=True),
    sa.Column('measurement', sa.String(), nullable=True),
    sa.Column('amount', sa.Numeric(), nullable=True),
    sa.Column('remainder', sa.Numeric(), nullable=True),
    sa.Column('price', sa.Numeric(), nullable=True),
    sa.Column('total_cost', sa.Numeric(), nullable=True),
    sa.Column('created_at', sa.Date(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('recipe', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_solutions'))
    )
    op.create_table('stock',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('substance_name', sa.String(length=255), nullable=False),
    sa.Column('measurement', sa.String(length=10), nullable=False),
    sa.Column('amount', sa.Numeric(), nullable=False),
    sa.Column('remainder', sa.Numeric(), nullable=True),
    sa.Column('price', sa.Numeric(), nullable=False),
    sa.Column('total_cost', sa.Numeric(), nullable=False),
    sa.Column('creation_date', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('normative', sa.String(length=255), nullable=True),
    sa.Column('recipe', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stock'))
    )
    op.create_table('substances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('measurement', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_substances')),
    sa.UniqueConstraint('name', name=op.f('uq_substances_name'))
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nickname', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('role', sa.String(length=10), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('substances')
    op.drop_table('stock')
    op.drop_table('solutions')
    op.drop_table('recipes')
    op.drop_table('normatives')
    op.drop_table('analysis')
    # ### end Alembic commands ###
