"""deleted active from solutions

Revision ID: fc5c28b31af6
Revises: bde6f82f8ad2
Create Date: 2020-11-30 18:43:30.907672

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc5c28b31af6'
down_revision = 'bde6f82f8ad2'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('solutions', 'action')
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('solutions', sa.Column('action', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
