"""modified back all Numeric fields, again without precision

Revision ID: 0e48ed321ab3
Revises: 70d7284acde4
Create Date: 2020-12-04 10:29:24.632561

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e48ed321ab3'
down_revision = '70d7284acde4'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
