"""added new models

Revision ID: b48290ef8bf1
Revises: 54324f7721ce
Create Date: 2020-11-28 14:11:03.346719

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b48290ef8bf1'
down_revision = '54324f7721ce'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
