"""try fix Numeric precision

Revision ID: c35928407e3d
Revises: 5b2e236e11f1
Create Date: 2020-12-01 20:13:06.366111

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c35928407e3d'
down_revision = '5b2e236e11f1'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
