"""added new fields to Analysis

Revision ID: c9e950192a0d
Revises: a7def787b281
Create Date: 2020-12-02 19:42:02.145467

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9e950192a0d'
down_revision = 'a7def787b281'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analysis', sa.Column('solutions_cost', sa.JSON(), nullable=True))
    op.add_column('analysis', sa.Column('substances_cost', sa.JSON(), nullable=True))
    op.add_column('analysis', sa.Column('total_cost', sa.Integer(), nullable=True))
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('analysis', 'total_cost')
    op.drop_column('analysis', 'substances_cost')
    op.drop_column('analysis', 'solutions_cost')
    # ### end Alembic commands ###
