"""removed field 'precursor from 'substances'

Revision ID: 12051e6a3e5f
Revises: 2670d0ff333a
Create Date: 2020-11-21 16:37:05.132476

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12051e6a3e5f'
down_revision = '2670d0ff333a'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
