"""modified stock table'



Revision ID: 3efe4292e631
Revises: 23be9196b1a5
Create Date: 2020-11-29 08:46:57.836706

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3efe4292e631'
down_revision = '23be9196b1a5'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stock', sa.Column('creation_date', sa.DateTime(), nullable=True))
    op.add_column('stock', sa.Column('notes', sa.Text(), nullable=True))
    op.add_column('stock', sa.Column('total_cost', sa.Numeric(), nullable=False))
    op.drop_column('stock', 'date')
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stock', sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('stock', 'total_cost')
    op.drop_column('stock', 'notes')
    op.drop_column('stock', 'creation_date')
    # ### end Alembic commands ###
