"""modified solutions table, added notes

Revision ID: bde6f82f8ad2
Revises: f03d5ae5d924
Create Date: 2020-11-29 19:33:49.933151

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bde6f82f8ad2'
down_revision = 'f03d5ae5d924'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('solutions', sa.Column('action', sa.String(), nullable=True))
    op.add_column('solutions', sa.Column('notes', sa.Text(), nullable=True))
    op.drop_column('solutions', 'user_id')
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('solutions', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('solutions', 'notes')
    op.drop_column('solutions', 'action')
    # ### end Alembic commands ###
