"""removed field

Revision ID: 54324f7721ce
Revises: bac6cdbeb7f9
Create Date: 2020-11-28 12:58:11.149226

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54324f7721ce'
down_revision = 'bac6cdbeb7f9'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('stock', 'substance_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('stock', 'substance_id')
    op.create_unique_constraint(op.f('uq_substances_name'), 'substances', ['name'])
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_substances_name'), 'substances', type_='unique')
    op.add_column('stock', sa.Column('substance_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.alter_column('stock', 'substance_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###
