"""added remainder fields

Revision ID: 70d7284acde4
Revises: c9e950192a0d
Create Date: 2020-12-02 21:56:51.425354

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70d7284acde4'
down_revision = 'c9e950192a0d'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('solutions', sa.Column('remainder', sa.Numeric(precision=11, scale=3), nullable=True))
    op.add_column('stock', sa.Column('remainder', sa.Numeric(precision=11, scale=3), nullable=True))
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stock', 'remainder')
    op.drop_column('solutions', 'remainder')
    # ### end Alembic commands ###
