"""changed JSON fields in recipes

Revision ID: 23be9196b1a5
Revises: 13e5a0220b25
Create Date: 2020-11-28 16:09:47.357109

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '23be9196b1a5'
down_revision = '13e5a0220b25'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipes', sa.Column('solutions', sa.JSON(), nullable=True))
    op.add_column('recipes', sa.Column('substances', sa.JSON(), nullable=True))
    op.drop_column('recipes', 'data')
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipes', sa.Column('data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('recipes', 'substances')
    op.drop_column('recipes', 'solutions')
    # ### end Alembic commands ###
