"""added fields 'active' to Substance and to Normative

Revision ID: 96c27aaa6ffa
Revises: 12051e6a3e5f
Create Date: 2020-11-24 19:21:20.021643

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96c27aaa6ffa'
down_revision = '12051e6a3e5f'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('normative', sa.Column('active', sa.Boolean(), nullable=True))
    op.add_column('substances', sa.Column('active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('substances', 'active')
    op.drop_column('normative', 'active')
    # ### end Alembic commands ###
