"""modified numeric fields

Revision ID: 5b2e236e11f1
Revises: fc5c28b31af6
Create Date: 2020-11-30 21:21:35.737282

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b2e236e11f1'
down_revision = 'fc5c28b31af6'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
