name: Trigger auto deployment for laboratory

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/laboratory-AutoDeployTrigger-e853d8ad-4b4d-4f4f-9ec2-843eebe3e20f.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.LABORATORY_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.LABORATORY_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.LABORATORY_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: laboratory123050b8d.azurecr.io
          registryUsername: ${{ secrets.LABORATORY_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.LABORATORY_REGISTRY_PASSWORD }}
          containerAppName: laboratory
          resourceGroup: laboratory123
          imageToBuild: laboratory123050b8d.azurecr.io/laboratory:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


